language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
install: npm install
sudo: false
after_success:
  npm run coverage
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
